
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 691355
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MyHashTable theTable = new MyHashTable(2);
    
    //constructor
    public MainFrame() {
        initComponents();
        mySettings();
    }
 

    public void mySettings () {
        addFullTime.setVisible(false);
        addPartTime.setVisible(false);
        missingFrame.setVisible(false);

        addFullTime.setSize(430,490);
        addPartTime.setSize(430,490);
        missingFrame.setSize(400,150);
    }
    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupAdd = new javax.swing.JPopupMenu();
        fullTime = new javax.swing.JMenuItem();
        partTime = new javax.swing.JMenuItem();
        addFullTime = new javax.swing.JFrame();
        fullTimeFristNameLabel = new javax.swing.JLabel();
        fullTimeLastNameLabel = new javax.swing.JLabel();
        fullTimeEmployeeNumberLabel = new javax.swing.JLabel();
        fullTimeDeductionRateLable = new javax.swing.JLabel();
        fullTimeSexLabel = new javax.swing.JLabel();
        fullTimeWorkLocationLabel = new javax.swing.JLabel();
        fullTimeLastNameTextField = new javax.swing.JTextField();
        fullTimeFirstNameTextField = new javax.swing.JTextField();
        fullTimeEmployeeNumberTextField = new javax.swing.JTextField();
        fullTimeDeductionRateTextField = new javax.swing.JTextField();
        fullTimeSexComboBox = new javax.swing.JComboBox<>();
        fullTimeWorkLocationComboBox = new javax.swing.JComboBox<>();
        fullTimeYearlySalaryLable = new javax.swing.JLabel();
        fullTimeYearlySalaryTextField = new javax.swing.JTextField();
        fullTimeAddButton = new javax.swing.JButton();
        fullTimeCancelButton = new javax.swing.JButton();
        fullTimeAgeLable = new javax.swing.JLabel();
        fullTimeAgeTextField = new javax.swing.JTextField();
        fullTimeAddedLabel = new javax.swing.JLabel();
        addPartTime = new javax.swing.JFrame();
        partTimeFristNameLabel = new javax.swing.JLabel();
        partTimeLastNameLabel = new javax.swing.JLabel();
        partTimeEmployeeNumberLabel = new javax.swing.JLabel();
        partTimeDeductionRateLable = new javax.swing.JLabel();
        partTimeSexLabel = new javax.swing.JLabel();
        partTimeWorkLocationLabel = new javax.swing.JLabel();
        partTimeLastNameTextField = new javax.swing.JTextField();
        partTimeFirstNameTextField = new javax.swing.JTextField();
        partTimeEmployeeNumberTextField = new javax.swing.JTextField();
        partTimeDeductionRateTextField = new javax.swing.JTextField();
        partTimeSexComboBox = new javax.swing.JComboBox<>();
        partTimeWorkLocationComboBox = new javax.swing.JComboBox<>();
        partTimeHourlyWageLable = new javax.swing.JLabel();
        partTimeHourlyWageTextField = new javax.swing.JTextField();
        partTimeHoursPerWeekLable = new javax.swing.JLabel();
        partTimeHoursPerWeekTextField = new javax.swing.JTextField();
        partTimeWeeksPerYearLable = new javax.swing.JLabel();
        partTimeWeeksPerYearTextField = new javax.swing.JTextField();
        partTimeAddButton = new javax.swing.JButton();
        partTimeCancelButton = new javax.swing.JButton();
        partTimeAgeTextField = new javax.swing.JTextField();
        fullTimeAgeLable1 = new javax.swing.JLabel();
        partTimeAddedLabel = new javax.swing.JLabel();
        missingFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        missingFrameOkButton = new javax.swing.JButton();
        removeFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        employeeNumTextBox = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        invalidEmployeeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hashTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        fullTime.setText("Add Full-Time Employee");
        fullTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeActionPerformed(evt);
            }
        });
        jPopupAdd.add(fullTime);

        partTime.setText("Add Part-Time Employee");
        partTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeActionPerformed(evt);
            }
        });
        jPopupAdd.add(partTime);

        addFullTime.setTitle("Add a Full-Time Employee");

        fullTimeFristNameLabel.setText("First Name");

        fullTimeLastNameLabel.setText("Last Name");

        fullTimeEmployeeNumberLabel.setText("Employee Number");

        fullTimeDeductionRateLable.setText("Deduction Rate");

        fullTimeSexLabel.setText("Sex");

        fullTimeWorkLocationLabel.setText("Work Location");

        fullTimeSexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        fullTimeWorkLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Ottawa", "Chicago" }));

        fullTimeYearlySalaryLable.setText("Yearly Salary");

        fullTimeAddButton.setText("Add");
        fullTimeAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullTimeAddButtonMouseExited(evt);
            }
        });
        fullTimeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeAddButtonActionPerformed(evt);
            }
        });

        fullTimeCancelButton.setText("Cancel");
        fullTimeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeCancelButtonActionPerformed(evt);
            }
        });

        fullTimeAgeLable.setText("Age");

        javax.swing.GroupLayout addFullTimeLayout = new javax.swing.GroupLayout(addFullTime.getContentPane());
        addFullTime.getContentPane().setLayout(addFullTimeLayout);
        addFullTimeLayout.setHorizontalGroup(
            addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFullTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                        .addComponent(fullTimeCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullTimeAddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                .addComponent(fullTimeAgeLable)
                                .addGap(18, 18, 18)
                                .addComponent(fullTimeAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fullTimeDeductionRateLable)
                                    .addComponent(fullTimeYearlySalaryLable))
                                .addGap(18, 18, 18)
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullTimeYearlySalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fullTimeSexLabel)
                                    .addComponent(fullTimeWorkLocationLabel)
                                    .addComponent(fullTimeEmployeeNumberLabel))
                                .addGap(18, 18, 18)
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                    .addComponent(fullTimeLastNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fullTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                    .addComponent(fullTimeFristNameLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(fullTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(addFullTimeLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(fullTimeAddedLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addFullTimeLayout.setVerticalGroup(
            addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFullTimeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeFristNameLabel))
                .addGap(14, 14, 14)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeLastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeEmployeeNumberLabel)
                    .addComponent(fullTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeSexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeWorkLocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeAgeLable))
                .addGap(10, 10, 10)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeDeductionRateLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeYearlySalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeYearlySalaryLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullTimeAddedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeCancelButton)
                    .addComponent(fullTimeAddButton))
                .addContainerGap())
        );

        addPartTime.setTitle("Add a Part-Time Employee");

        partTimeFristNameLabel.setText("First Name");

        partTimeLastNameLabel.setText("Last Name");

        partTimeEmployeeNumberLabel.setText("Employee Number");

        partTimeDeductionRateLable.setText("Deduction Rate");

        partTimeSexLabel.setText("Sex");

        partTimeWorkLocationLabel.setText("Work Location");

        partTimeSexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Male", "Female" }));

        partTimeWorkLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Ottawa", "Chicago" }));

        partTimeHourlyWageLable.setText("Hourly Wage");

        partTimeHoursPerWeekLable.setText("Hours per Week");

        partTimeWeeksPerYearLable.setText("Weeks per Year");

        partTimeAddButton.setText("Add");
        partTimeAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                partTimeAddButtonMouseExited(evt);
            }
        });
        partTimeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeAddButtonActionPerformed(evt);
            }
        });

        partTimeCancelButton.setText("Cancel");
        partTimeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeCancelButtonActionPerformed(evt);
            }
        });

        fullTimeAgeLable1.setText("Age");

        javax.swing.GroupLayout addPartTimeLayout = new javax.swing.GroupLayout(addPartTime.getContentPane());
        addPartTime.getContentPane().setLayout(addPartTimeLayout);
        addPartTimeLayout.setHorizontalGroup(
            addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPartTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                        .addComponent(partTimeCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(partTimeAddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeLastNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeFristNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeDeductionRateLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(partTimeEmployeeNumberLabel)
                                    .addComponent(partTimeSexLabel)
                                    .addComponent(partTimeWorkLocationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(partTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeHourlyWageLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeHoursPerWeekLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeWeeksPerYearLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(fullTimeAgeLable1)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(partTimeAddedLabel)
                .addGap(180, 180, 180))
        );
        addPartTimeLayout.setVerticalGroup(
            addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPartTimeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeFristNameLabel))
                .addGap(14, 14, 14)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeLastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeEmployeeNumberLabel)
                    .addComponent(partTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeSexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeWorkLocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeAgeLable1))
                .addGap(13, 13, 13)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeDeductionRateLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeHourlyWageLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeHoursPerWeekLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeWeeksPerYearLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partTimeAddedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeAddButton)
                    .addComponent(partTimeCancelButton))
                .addContainerGap())
        );

        jLabel1.setText("Some of the form is missing!");

        missingFrameOkButton.setText("OK");
        missingFrameOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missingFrameOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout missingFrameLayout = new javax.swing.GroupLayout(missingFrame.getContentPane());
        missingFrame.getContentPane().setLayout(missingFrameLayout);
        missingFrameLayout.setHorizontalGroup(
            missingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missingFrameLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, missingFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(missingFrameOkButton)
                .addContainerGap())
        );
        missingFrameLayout.setVerticalGroup(
            missingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missingFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(missingFrameOkButton))
        );

        removeFrame.setBounds(new java.awt.Rectangle(370, 400, 400, 400));
        removeFrame.setResizable(false);

        jLabel2.setText("Employee Number");

        employeeNumTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumTextBoxActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.setMaximumSize(new java.awt.Dimension(300, 400));
        confirmButton.setMinimumSize(new java.awt.Dimension(300, 400));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeFrameLayout = new javax.swing.GroupLayout(removeFrame.getContentPane());
        removeFrame.getContentPane().setLayout(removeFrameLayout);
        removeFrameLayout.setHorizontalGroup(
            removeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFrameLayout.createSequentialGroup()
                .addGroup(removeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeFrameLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeNumTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeFrameLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(invalidEmployeeLabel))
                    .addGroup(removeFrameLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        removeFrameLayout.setVerticalGroup(
            removeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFrameLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(removeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeNumTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(invalidEmployeeLabel)
                .addGap(40, 40, 40)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDMS - Employee Database Management System");

        hashTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Employee Number", "Work Location"
            }
        ));
        jScrollPane2.setViewportView(hashTable);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(262, 262, 262)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
//        DefaultTableModel model=(DefaultTableModel) hashTable.getModel();
//        
//        model.addRow(new Object[] {})
        jPopupAdd.show(this,addButton.getX(),addButton.getY());
    }//GEN-LAST:event_addButtonActionPerformed

    private void fullTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeActionPerformed
        addFullTime.setVisible(true);
        fullTimeAddedLabel.setText("");
        
    }//GEN-LAST:event_fullTimeActionPerformed

    private void partTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeActionPerformed
        addPartTime.setVisible(true);
        
    }//GEN-LAST:event_partTimeActionPerformed

    private void partTimeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeCancelButtonActionPerformed
        addPartTime.setVisible(false);
        partTimeFirstNameTextField.setText("");
        partTimeLastNameTextField.setText("");
        partTimeAgeTextField.setText("");
        partTimeEmployeeNumberTextField.setText("");
        partTimeDeductionRateTextField.setText("");
        partTimeHourlyWageTextField.setText("");
        partTimeHoursPerWeekTextField.setText("");
        partTimeWeeksPerYearTextField.setText("");

    }//GEN-LAST:event_partTimeCancelButtonActionPerformed

    private void fullTimeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeCancelButtonActionPerformed
        addFullTime.setVisible(false);
        fullTimeFirstNameTextField.setText("");
        fullTimeLastNameTextField.setText("");
        fullTimeEmployeeNumberTextField.setText("");
        fullTimeAgeTextField.setText("");
        fullTimeDeductionRateTextField.setText("");
        fullTimeYearlySalaryTextField.setText("");
    }//GEN-LAST:event_fullTimeCancelButtonActionPerformed

    private void fullTimeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeAddButtonActionPerformed
        if (fullTimeFirstNameTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (fullTimeLastNameTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (fullTimeEmployeeNumberTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (fullTimeAgeTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (fullTimeDeductionRateTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (fullTimeYearlySalaryTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else {

         FullTimeEmployee somebody;
         somebody = new FullTimeEmployee (Integer.parseInt(fullTimeAgeTextField.getText()), 
                                          Integer.parseInt(fullTimeEmployeeNumberTextField.getText()),
                                          fullTimeSexComboBox.getSelectedIndex(),
                                          fullTimeWorkLocationComboBox.getSelectedIndex(),
                                          Double.parseDouble(fullTimeDeductionRateTextField.getText()),
                                          fullTimeFirstNameTextField.getText(),
                                          fullTimeLastNameTextField.getText(),
                                          Double.parseDouble(fullTimeYearlySalaryTextField.getText()));
         theTable.addToHashTable(somebody);
         
        fullTimeFirstNameTextField.setText("");
        fullTimeLastNameTextField.setText("");
        fullTimeEmployeeNumberTextField.setText("");
        fullTimeAgeTextField.setText("");
        fullTimeDeductionRateTextField.setText("");
        fullTimeYearlySalaryTextField.setText("");
        
        
        fullTimeAddedLabel.setText("Employee has added.");
        }
    }//GEN-LAST:event_fullTimeAddButtonActionPerformed

    private void partTimeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeAddButtonActionPerformed
        if (partTimeFirstNameTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeLastNameTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeEmployeeNumberTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeAgeTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeDeductionRateTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeHourlyWageTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeHoursPerWeekTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else if (partTimeWeeksPerYearTextField.getText().isEmpty()) {
            missingFrame.setVisible(true);
        } else {
         
         PartTimeEmployee somebody;
         somebody = new PartTimeEmployee (Integer.parseInt(partTimeAgeTextField.getText()), 
                                          Integer.parseInt(partTimeEmployeeNumberTextField.getText()),
                                          partTimeSexComboBox.getSelectedIndex(),
                                          partTimeWorkLocationComboBox.getSelectedIndex(),
                                          Double.parseDouble(partTimeDeductionRateTextField.getText()),
                                          partTimeFirstNameTextField.getText(),
                                          partTimeLastNameTextField.getText(),
                                          Double.parseDouble(partTimeHourlyWageTextField.getText()),
                                          Double.parseDouble(partTimeHoursPerWeekTextField.getText()),
                                          Double.parseDouble(partTimeWeeksPerYearTextField.getText()));
         theTable.addToHashTable(somebody);
         
        partTimeFirstNameTextField.setText("");
        partTimeLastNameTextField.setText("");
        partTimeAgeTextField.setText("");
        partTimeEmployeeNumberTextField.setText("");
        partTimeDeductionRateTextField.setText("");
        partTimeHourlyWageTextField.setText("");
        partTimeHoursPerWeekTextField.setText("");
        partTimeWeeksPerYearTextField.setText("");
        partTimeAddedLabel.setText("Employee has been added");
        }
    }//GEN-LAST:event_partTimeAddButtonActionPerformed

    private void missingFrameOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missingFrameOkButtonActionPerformed
        missingFrame.dispose();
    }//GEN-LAST:event_missingFrameOkButtonActionPerformed

    private void fullTimeAddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullTimeAddButtonMouseExited
        fullTimeAddedLabel.setText("");
    }//GEN-LAST:event_fullTimeAddButtonMouseExited

    private void partTimeAddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partTimeAddButtonMouseExited
        partTimeAddedLabel.setText("");
    }//GEN-LAST:event_partTimeAddButtonMouseExited

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        removeFrame.setVisible(true);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void employeeNumTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumTextBoxActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if (theTable.findIndex(Integer.parseInt(employeeNumTextBox.getText())) == -1) {
            invalidEmployeeLabel.setText("The entered employee does not exist");
        }
        
        else {
        theTable.removeFromHashTable(Integer.parseInt(employeeNumTextBox.getText()));
        removeFrame.setVisible(false);
        employeeNumTextBox.setText(null);
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        String dataFile = "D://Netbeans Projects//EmployeeDataBaseICS4U0//src//data//data.txt.";
        
        try {
            FileWriter fileWriter = new FileWriter(dataFile);
            BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
            
		for (int i = 0; i < theTable.getHashTable().length; i++) {
			
			for (int j = 0; j < theTable.getHashTable()[i].size();j++)
			{
				bufferedWriter.write(Integer.toString(theTable.getHashTable()[i].get(j).getAge()));
                                bufferedWriter.write(Integer.toString(theTable.getHashTable()[i].get(j).getEmployeeNumber()));
                                bufferedWriter.write(Integer.toString(theTable.getHashTable()[i].get(j).getSex()));
                                bufferedWriter.write(Integer.toString(theTable.getHashTable()[i].get(j).getWorkLocation()));
                                bufferedWriter.write(Double.toString(theTable.getHashTable()[i].get(j).getDeductionsRate()));
                                bufferedWriter.write(theTable.getHashTable()[i].get(j).getFirstName());
                                bufferedWriter.write(theTable.getHashTable()[i].get(j).getLastName());
                                bufferedWriter.write(Double.toString(theTable.getHashTable()[i].get(j).calcAnnualGrossIncome()));
                                
                                //System.out.println(theTable.getHashTable()[i].get(j).getAge());
			}
			
		}
            bufferedWriter.close();
            /*
            Integer.parseInt(fullTimeAgeTextField.getText()),
                                          Integer.parseInt(fullTimeEmployeeNumberTextField.getText()),
                                          fullTimeSexComboBox.getSelectedIndex(),
                                          fullTimeWorkLocationComboBox.getSelectedIndex(),
                                          Double.parseDouble(fullTimeDeductionRateTextField.getText()),
                                          fullTimeFirstNameTextField.getText(),
                                          fullTimeLastNameTextField.getText(),
                                          Double.parseDouble(fullTimeYearlySalaryTextField.getText()))
            
            */
            
        } catch (IOException ex) {
            System.out.println("you fucked up, couldn't write to '" + dataFile + "'");
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JFrame addFullTime;
    private javax.swing.JFrame addPartTime;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField employeeNumTextBox;
    private javax.swing.JMenuItem fullTime;
    private javax.swing.JButton fullTimeAddButton;
    private javax.swing.JLabel fullTimeAddedLabel;
    private javax.swing.JLabel fullTimeAgeLable;
    private javax.swing.JLabel fullTimeAgeLable1;
    private javax.swing.JTextField fullTimeAgeTextField;
    private javax.swing.JButton fullTimeCancelButton;
    private javax.swing.JLabel fullTimeDeductionRateLable;
    private javax.swing.JTextField fullTimeDeductionRateTextField;
    private javax.swing.JLabel fullTimeEmployeeNumberLabel;
    private javax.swing.JTextField fullTimeEmployeeNumberTextField;
    private javax.swing.JTextField fullTimeFirstNameTextField;
    private javax.swing.JLabel fullTimeFristNameLabel;
    private javax.swing.JLabel fullTimeLastNameLabel;
    private javax.swing.JTextField fullTimeLastNameTextField;
    private javax.swing.JComboBox<String> fullTimeSexComboBox;
    private javax.swing.JLabel fullTimeSexLabel;
    private javax.swing.JComboBox<String> fullTimeWorkLocationComboBox;
    private javax.swing.JLabel fullTimeWorkLocationLabel;
    private javax.swing.JLabel fullTimeYearlySalaryLable;
    private javax.swing.JTextField fullTimeYearlySalaryTextField;
    private javax.swing.JTable hashTable;
    private javax.swing.JLabel invalidEmployeeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupAdd;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFrame missingFrame;
    private javax.swing.JButton missingFrameOkButton;
    private javax.swing.JMenuItem partTime;
    private javax.swing.JButton partTimeAddButton;
    private javax.swing.JLabel partTimeAddedLabel;
    private javax.swing.JTextField partTimeAgeTextField;
    private javax.swing.JButton partTimeCancelButton;
    private javax.swing.JLabel partTimeDeductionRateLable;
    private javax.swing.JTextField partTimeDeductionRateTextField;
    private javax.swing.JLabel partTimeEmployeeNumberLabel;
    private javax.swing.JTextField partTimeEmployeeNumberTextField;
    private javax.swing.JTextField partTimeFirstNameTextField;
    private javax.swing.JLabel partTimeFristNameLabel;
    private javax.swing.JLabel partTimeHourlyWageLable;
    private javax.swing.JTextField partTimeHourlyWageTextField;
    private javax.swing.JLabel partTimeHoursPerWeekLable;
    private javax.swing.JTextField partTimeHoursPerWeekTextField;
    private javax.swing.JLabel partTimeLastNameLabel;
    private javax.swing.JTextField partTimeLastNameTextField;
    private javax.swing.JComboBox<String> partTimeSexComboBox;
    private javax.swing.JLabel partTimeSexLabel;
    private javax.swing.JLabel partTimeWeeksPerYearLable;
    private javax.swing.JTextField partTimeWeeksPerYearTextField;
    private javax.swing.JComboBox<String> partTimeWorkLocationComboBox;
    private javax.swing.JLabel partTimeWorkLocationLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JFrame removeFrame;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
