
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 691355
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        mySettings();
    }

    public void mySettings () {
        addFullTime.setVisible(false);
        addPartTime.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupAdd = new javax.swing.JPopupMenu();
        fullTime = new javax.swing.JMenuItem();
        partTime = new javax.swing.JMenuItem();
        addFullTime = new javax.swing.JFrame();
        fullTimeFristNameLabel = new javax.swing.JLabel();
        fullTimeLastNameLabel = new javax.swing.JLabel();
        fullTimeEmployeeNumberLabel = new javax.swing.JLabel();
        fullTimeDeductionRateLable = new javax.swing.JLabel();
        fullTimeSexLabel = new javax.swing.JLabel();
        fullTimeWorkLocationLabel = new javax.swing.JLabel();
        fullTimeLastNameTextField = new javax.swing.JTextField();
        fullTimeFirstNameTextField = new javax.swing.JTextField();
        fullTimeEmployeeNumberTextField = new javax.swing.JTextField();
        fullTimeDeductionRateTextField = new javax.swing.JTextField();
        fullTimeSexComboBox = new javax.swing.JComboBox<>();
        fullTimeWorkLocationComboBox = new javax.swing.JComboBox<>();
        fullTimeYearlySalaryLable = new javax.swing.JLabel();
        fullTimeYearlySalaryTextField = new javax.swing.JTextField();
        fullTimeAddButton = new javax.swing.JButton();
        fullTimeCancelButton = new javax.swing.JButton();
        fullTimeAgeLable = new javax.swing.JLabel();
        fullTimeAgeTextField = new javax.swing.JTextField();
        addPartTime = new javax.swing.JFrame();
        partTimeFristNameLabel = new javax.swing.JLabel();
        partTimeLastNameLabel = new javax.swing.JLabel();
        partTimeEmployeeNumberLabel = new javax.swing.JLabel();
        partTimeDeductionRateLable = new javax.swing.JLabel();
        partTimeSexLabel = new javax.swing.JLabel();
        partTimeWorkLocationLabel = new javax.swing.JLabel();
        partTimeLastNameTextField = new javax.swing.JTextField();
        partTimeFirstNameTextField = new javax.swing.JTextField();
        partTimeEmployeeNumberTextField = new javax.swing.JTextField();
        partTimeDeductionRateTextField = new javax.swing.JTextField();
        partTimeSexComboBox = new javax.swing.JComboBox<>();
        partTimeWorkLocationComboBox = new javax.swing.JComboBox<>();
        partTimeHourlyWageLable = new javax.swing.JLabel();
        partTimeHourlyWageTextField = new javax.swing.JTextField();
        partTimeHoursPerWeekLable = new javax.swing.JLabel();
        partTimeHoursPerWeekTextField = new javax.swing.JTextField();
        partTimeWeeksPerYearLable = new javax.swing.JLabel();
        partTimeWeeksPerYearTextField = new javax.swing.JTextField();
        partTimeAddButton = new javax.swing.JButton();
        partTimeCancelButton = new javax.swing.JButton();
        fullTimeAgeTextField1 = new javax.swing.JTextField();
        fullTimeAgeLable1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hashTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();

        fullTime.setText("Add Full-Time Employee");
        fullTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeActionPerformed(evt);
            }
        });
        jPopupAdd.add(fullTime);

        partTime.setText("Add Part-Time Employee");
        partTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeActionPerformed(evt);
            }
        });
        jPopupAdd.add(partTime);

        fullTimeFristNameLabel.setText("First Name");

        fullTimeLastNameLabel.setText("Last Name");

        fullTimeEmployeeNumberLabel.setText("Employee Number");

        fullTimeDeductionRateLable.setText("Deduction Rate");

        fullTimeSexLabel.setText("Sex");

        fullTimeWorkLocationLabel.setText("Work Location");

        fullTimeSexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Male", "Female" }));

        fullTimeWorkLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Ottawa", "Chicago" }));

        fullTimeYearlySalaryLable.setText("Yearly Salary");

        fullTimeAddButton.setText("Add");
        fullTimeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeAddButtonActionPerformed(evt);
            }
        });

        fullTimeCancelButton.setText("Cancel");
        fullTimeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeCancelButtonActionPerformed(evt);
            }
        });

        fullTimeAgeLable.setText("Age");

        javax.swing.GroupLayout addFullTimeLayout = new javax.swing.GroupLayout(addFullTime.getContentPane());
        addFullTime.getContentPane().setLayout(addFullTimeLayout);
        addFullTimeLayout.setHorizontalGroup(
            addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFullTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                        .addComponent(fullTimeCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullTimeAddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                .addComponent(fullTimeAgeLable)
                                .addGap(18, 18, 18)
                                .addComponent(fullTimeAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fullTimeDeductionRateLable)
                                    .addComponent(fullTimeYearlySalaryLable))
                                .addGap(18, 18, 18)
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullTimeYearlySalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fullTimeSexLabel)
                                    .addComponent(fullTimeWorkLocationLabel)
                                    .addComponent(fullTimeEmployeeNumberLabel))
                                .addGap(18, 18, 18)
                                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                    .addComponent(fullTimeLastNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fullTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFullTimeLayout.createSequentialGroup()
                                    .addComponent(fullTimeFristNameLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(fullTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        addFullTimeLayout.setVerticalGroup(
            addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFullTimeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeFristNameLabel))
                .addGap(14, 14, 14)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeLastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeEmployeeNumberLabel)
                    .addComponent(fullTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeSexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeWorkLocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeAgeLable))
                .addGap(10, 10, 10)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeDeductionRateLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeYearlySalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeYearlySalaryLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(addFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeCancelButton)
                    .addComponent(fullTimeAddButton))
                .addContainerGap())
        );

        partTimeFristNameLabel.setText("First Name");

        partTimeLastNameLabel.setText("Last Name");

        partTimeEmployeeNumberLabel.setText("Employee Number");

        partTimeDeductionRateLable.setText("Deduction Rate");

        partTimeSexLabel.setText("Sex");

        partTimeWorkLocationLabel.setText("Work Location");

        partTimeSexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Male", "Female" }));

        partTimeWorkLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Ottawa", "Chicago" }));

        partTimeHourlyWageLable.setText("Hourly Wage");

        partTimeHoursPerWeekLable.setText("Hours per Week");

        partTimeWeeksPerYearLable.setText("Weeks per Year");

        partTimeAddButton.setText("Add");

        partTimeCancelButton.setText("Cancel");
        partTimeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeCancelButtonActionPerformed(evt);
            }
        });

        fullTimeAgeLable1.setText("Age");

        javax.swing.GroupLayout addPartTimeLayout = new javax.swing.GroupLayout(addPartTime.getContentPane());
        addPartTime.getContentPane().setLayout(addPartTimeLayout);
        addPartTimeLayout.setHorizontalGroup(
            addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPartTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                        .addComponent(partTimeCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(partTimeAddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeLastNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeFristNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeDeductionRateLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(partTimeEmployeeNumberLabel)
                                    .addComponent(partTimeSexLabel)
                                    .addComponent(partTimeWorkLocationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(partTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeHourlyWageLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeHoursPerWeekLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(partTimeWeeksPerYearLable)
                                .addGap(18, 18, 18)
                                .addComponent(partTimeWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPartTimeLayout.createSequentialGroup()
                                .addComponent(fullTimeAgeLable1)
                                .addGap(18, 18, 18)
                                .addComponent(fullTimeAgeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        addPartTimeLayout.setVerticalGroup(
            addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPartTimeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeFristNameLabel))
                .addGap(14, 14, 14)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeLastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeEmployeeNumberLabel)
                    .addComponent(partTimeEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeSexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeWorkLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeWorkLocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeAgeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeAgeLable1))
                .addGap(13, 13, 13)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeDeductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeDeductionRateLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeHourlyWageLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeHoursPerWeekLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeWeeksPerYearLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(addPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeAddButton)
                    .addComponent(partTimeCancelButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hashTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Employee Number", "Work Location", "Sex", "Age"
            }
        ));
        jScrollPane2.setViewportView(hashTable);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(addButton)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
//        DefaultTableModel model=(DefaultTableModel) hashTable.getModel();
//        
//        model.addRow(new Object[] {})
        jPopupAdd.show(this,addButton.getX(),addButton.getY());
    }//GEN-LAST:event_addButtonActionPerformed

    private void fullTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeActionPerformed
        addFullTime.setVisible(true);
        addFullTime.setSize(425,480);
    }//GEN-LAST:event_fullTimeActionPerformed

    private void partTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeActionPerformed
        addPartTime.setVisible(true);
        addPartTime.setSize(425,480);
    }//GEN-LAST:event_partTimeActionPerformed

    private void partTimeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeCancelButtonActionPerformed
        addPartTime.setVisible(false);
        partTimeFirstNameTextField.setText("");
        partTimeLastNameTextField.setText("");
        partTimeEmployeeNumberTextField.setText("");
        partTimeDeductionRateTextField.setText("");
        partTimeHourlyWageTextField.setText("");
        partTimeHoursPerWeekTextField.setText("");
        partTimeWeeksPerYearTextField.setText("");
    }//GEN-LAST:event_partTimeCancelButtonActionPerformed

    private void fullTimeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeCancelButtonActionPerformed
        addFullTime.setVisible(false);
        fullTimeFirstNameTextField.setText("");
        fullTimeLastNameTextField.setText("");
        fullTimeEmployeeNumberTextField.setText("");
        fullTimeDeductionRateTextField.setText("");
        fullTimeYearlySalaryTextField.setText("");
    }//GEN-LAST:event_fullTimeCancelButtonActionPerformed

    private void fullTimeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeAddButtonActionPerformed
        
    }//GEN-LAST:event_fullTimeAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JFrame addFullTime;
    private javax.swing.JFrame addPartTime;
    private javax.swing.JMenuItem fullTime;
    private javax.swing.JButton fullTimeAddButton;
    private javax.swing.JLabel fullTimeAgeLable;
    private javax.swing.JLabel fullTimeAgeLable1;
    private javax.swing.JTextField fullTimeAgeTextField;
    private javax.swing.JTextField fullTimeAgeTextField1;
    private javax.swing.JButton fullTimeCancelButton;
    private javax.swing.JLabel fullTimeDeductionRateLable;
    private javax.swing.JTextField fullTimeDeductionRateTextField;
    private javax.swing.JLabel fullTimeEmployeeNumberLabel;
    private javax.swing.JTextField fullTimeEmployeeNumberTextField;
    private javax.swing.JTextField fullTimeFirstNameTextField;
    private javax.swing.JLabel fullTimeFristNameLabel;
    private javax.swing.JLabel fullTimeLastNameLabel;
    private javax.swing.JTextField fullTimeLastNameTextField;
    private javax.swing.JComboBox<String> fullTimeSexComboBox;
    private javax.swing.JLabel fullTimeSexLabel;
    private javax.swing.JComboBox<String> fullTimeWorkLocationComboBox;
    private javax.swing.JLabel fullTimeWorkLocationLabel;
    private javax.swing.JLabel fullTimeYearlySalaryLable;
    private javax.swing.JTextField fullTimeYearlySalaryTextField;
    private javax.swing.JTable hashTable;
    private javax.swing.JPopupMenu jPopupAdd;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem partTime;
    private javax.swing.JButton partTimeAddButton;
    private javax.swing.JButton partTimeCancelButton;
    private javax.swing.JLabel partTimeDeductionRateLable;
    private javax.swing.JTextField partTimeDeductionRateTextField;
    private javax.swing.JLabel partTimeEmployeeNumberLabel;
    private javax.swing.JTextField partTimeEmployeeNumberTextField;
    private javax.swing.JTextField partTimeFirstNameTextField;
    private javax.swing.JLabel partTimeFristNameLabel;
    private javax.swing.JLabel partTimeHourlyWageLable;
    private javax.swing.JTextField partTimeHourlyWageTextField;
    private javax.swing.JLabel partTimeHoursPerWeekLable;
    private javax.swing.JTextField partTimeHoursPerWeekTextField;
    private javax.swing.JLabel partTimeLastNameLabel;
    private javax.swing.JTextField partTimeLastNameTextField;
    private javax.swing.JComboBox<String> partTimeSexComboBox;
    private javax.swing.JLabel partTimeSexLabel;
    private javax.swing.JLabel partTimeWeeksPerYearLable;
    private javax.swing.JTextField partTimeWeeksPerYearTextField;
    private javax.swing.JComboBox<String> partTimeWorkLocationComboBox;
    private javax.swing.JLabel partTimeWorkLocationLabel;
    // End of variables declaration//GEN-END:variables
}
